### ISSUE TITLE
SonicPi - expired SSL

### ISSUE THREAD

**Issue by macmule** [autopkg/aanklewicz-recipes#16]
FYI, downloads are failing as the SSL cert for https://sonic-pi.net has expired.

**Comment by aanklewicz** [comment]
Thanks Ben, I've opened an issue on Sonic Pi's Github. Seems to be happening every 90 days, looking at past issues.

**Comment by aanklewicz** [comment]
They've renewed the cert.

**Comment by aanklewicz** [comment]
Merged changes, closing issue.
